version: '3'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST= dev-martin-marinov.com
      - LETSENCRYPT_HOST= dev-martin-marinov.com